import = [
   "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font Mono"

[window]
opacity = 0.9
decorations = "buttonless"

[env]
TERM = "xterm-256color"
